version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-fiber-redis
    ports:
      - "3000:3000"
    depends_on: 
      - redis

